version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - retro-network
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_URL=${SERVER_URL}
    command: npm start
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - retro-network
    volumes:
      - ./server/src:/usr/app/src

    environment:
      - MONGO_URI=${MONGO_URI}
      - CLIENT_URL=${CLIENT_URL}
    command: npm start

networks:
  retro-network:
    driver: bridge
