export const CREATE_ITEM_REQUESTED = "CREATE_ITEM_REQUESTED";
export const REORDER_ITEM_REQUESTED = "REORDER_ITEM_REQUESTED";
export const DELETE_ITEM_REQUESTED = "DELETE_ITEM_REQUESTED";
export const UPDATE_ITEM_REQUESTED = "UPDATE_ITEM_REQUESTED";

export const FETCH_BOARDS_REQUESTED = "FETCH_BOARDS_REQUESTED";
export const CREATE_BOARD_REQUESTED = "CREATE_BOARD_REQUESTED";
export const FETCH_BOARD_REQUESTED = "FETCH_BOARD_REQUESTED";
export const DELETE_BOARD_REQUESTED = "DELETE_BOARD_REQUESTED";
export const UPDATE_BOARD_REQUESTED = "UPDATE_BOARD_REQUESTED";

export const CREATE_LIST_REQUESTED = "CREATE_LIST_REQUESTED";
export const UPDATE_LIST_REQUESTED = "UPDATE_LIST_REQUESTED";
